version: "3.8"

services:
  postgres:
    build: ./database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: annelida_collection_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/scripts/change-date.sql:/docker-entrypoint-initdb.d/change-date.sql
      - ./database/scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./database/scripts/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql

